#!/usr/bin/env python3

import os
import sys

templ = """/*
:name: {1}_assignment
:description: {0} assignment test
:should_fail: 0
:tags: 11.4.1
*/
module top();

int a = 12;
int b = 5;

initial begin
    a {0} b;
end

endmodule
"""

ops = [
    ('=', 'normal'),
    ('+=', 'plus'),
    ('-=', 'minus'),
    ('*=', 'mul'),
    ('/=', 'div'),
    ('%=', 'mod'),
    ('&=', 'and'),
    ('|=', 'or'),
    ('^=', 'xor'),
    ('<<=', 'log_shl'),
    ('>>=', 'log_shr'),
    ('<<<=', 'arith_shl'),
    ('>>>=', 'arith_shr'),
]

try:
    tests_dir = os.environ['TESTS_DIR']
    conf_dir = os.environ['CONF_DIR']
except KeyError:
    print("Export the TESTS_DIR and CONF_DIR variables first")
    sys.exit(1)

try:
    tests_subdir = sys.argv[1]
except IndexError:
    print("Usage: ./generator <subdir>")
    sys.exit(1)

for op in ops:
    test_file = os.path.join(tests_dir,
                             "generated",
                             tests_subdir,
                             "11.4.1--" + op[1] + "_assignment.sv")
    with open(test_file, "w") as wf:
        wf.write(templ.format(*op))
