#!/usr/bin/env python3

import os
import sys

templ = """/*
:name: binary_op_{1}
:description: {0} operator test
:should_fail: 0
:tags: {2}
*/
module top();

int a = 12;
int b = 5;
int c;

initial begin
    c = a {0} b;
end

endmodule
"""

ops = [
    ('+', 'plus', '11.4.3'),
    ('-', 'minus', '11.4.3'),
    ('*', 'mul', '11.4.3'),
    ('/', 'div', '11.4.3'),
    ('%', 'mod', '11.4.3'),
    ('==', 'log_eq', '11.4.5'),
    ('!=', 'log_neq', '11.4.5'),
    ('===', 'case_eq', '11.4.5'),
    ('!==', 'case_neq', '11.4.5'),
    ('==?', 'wild_eq', '11.4.6'),
    ('!=?', 'wild_neq', '11.4.6'),
    ('&&', 'log_and', '11.4.7'),
    ('||', 'log_or', '11.4.7'),
    ('**', 'pow', '11.4.3'),
    ('<', 'lt', '11.4.4'),
    ('<=', 'le', '11.4.4'),
    ('>', 'gt', '11.4.4'),
    ('>=', 'ge', '11.4.4'),
    ('&', 'bit_and', '11.4.8'),
    ('|', 'bit_or', '11.4.8'),
    ('^', 'bit_xor', '11.4.8'),
    ('^~', 'bit_xnor', '11.4.8'),
    ('~^', 'bit_xnor', '11.4.8'),
    ('>>', 'log_shr', '11.4.10'),
    ('<<', 'log_shl', '11.4.10'),
    ('>>>', 'arith_shr', '11.4.10'),
    ('<<<', 'arith_shl', '11.4.10'),
    ('->', 'log_imp', '11.4.7'),
    ('<->', 'log_eq', '11.4.7'),
]

try:
    tests_dir = os.environ['TESTS_DIR']
    conf_dir = os.environ['CONF_DIR']
except KeyError:
    print("Export the TESTS_DIR and CONF_DIR variables first")
    sys.exit(1)

try:
    tests_subdir = sys.argv[1]
except IndexError:
    print("Usage: ./generator <subdir>")
    sys.exit(1)

for op in ops:
    test_file = os.path.join(tests_dir,
                             "generated",
                             tests_subdir,
                             "{2}--binary_op_{1}.sv".format(*op))
    with open(test_file, "w") as wf:
        wf.write(templ.format(*op))
