#!/usr/bin/env python3

import os
import re
import sys
import subprocess

templ = """/*
:name: earlgrey
:description: Earlgrey design from opentitan
:files: {0}
:incdirs: {1}
:tags: earlgrey
:timeout: 180
:top_module: top_earlgrey_nexysvideo
*/
"""

try:
    third_party_dir = os.environ['THIRD_PARTY_DIR']
    tests_dir = os.environ['TESTS_DIR']
    conf_dir = os.environ['CONF_DIR']
except KeyError:
    print("Export the THIRD_PARTY_DIR, TESTS_DIR and CONF_DIR variables first")
    sys.exit(1)

try:
    tests_subdir = sys.argv[1]
except IndexError:
    print("Usage: ./generator <subdir>")
    sys.exit(1)

earlgrey_path = os.path.abspath(
    os.path.join(third_party_dir, "cores", "opentitan"))

sources = ''
incdirs = ''
incs = []

subprocess.call(
    [
        "fusesoc", "--cores-root", earlgrey_path, "sim",
        "lowrisc:systems:top_earlgrey:0.1"
    ],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL)

earlgrey_conf_path = os.path.abspath(
    os.path.join("build", "lowrisc_systems_top_earlgrey_0.1", "sim-icarus"))

with open(os.path.join(earlgrey_conf_path,
                       'lowrisc_systems_top_earlgrey_0.1.scr'), "r") as f:
    for line in f:
        line = line.strip()
        if "+incdir+" in line:
            line = line.replace('+incdir+', '')
            incs.append(
                os.path.dirname(os.path.join(earlgrey_conf_path, line)))
            continue
        elif "+define+" in line:
            continue

        incs.append(os.path.dirname(os.path.join(earlgrey_conf_path, line)))
        sources += os.path.join(earlgrey_conf_path, line) + ' '

incs = list(dict.fromkeys(incs))
for line in incs:
    incdirs += line + ' '

test_dir = os.path.join(tests_dir, 'generated', tests_subdir)

if not os.path.isdir(test_dir):
    os.makedirs(test_dir, exist_ok=True)

test_file = os.path.join(test_dir, "earlgrey.sv")

with open(test_file, "w") as f:
    f.write(templ.format(sources, incdirs))
