#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC

import os
import sys
import yaml

templ = """/*
:name: easyUVM
:description: UVM testbench test
:files: {0}
:incdirs: {1}
:tags: uvm
:timeout: 300
:unsynthesizable: 1
*/
"""

try:
    third_party_dir = os.environ['THIRD_PARTY_DIR']
    tests_dir = os.environ['TESTS_DIR']
    conf_dir = os.environ['CONF_DIR']
except KeyError:
    print("Export the THIRD_PARTY_DIR, TESTS_DIR and CONF_DIR variables first")
    sys.exit(1)

try:
    tests_subdir = sys.argv[1]
except IndexError:
    print("Usage: ./generator <subdir>")
    sys.exit(1)

uvm_path = os.path.abspath(os.path.join(third_party_dir, "tests", "easyUVM"))

sources = os.path.join(uvm_path, 'top.sv')
incdirs = uvm_path

test_dir = os.path.join(tests_dir, 'generated', tests_subdir)

if not os.path.isdir(test_dir):
    os.makedirs(test_dir, exist_ok=True)

test_file = os.path.join(test_dir, "top.sv")

with open(test_file, "w") as f:
    f.write(templ.format(sources, incdirs))
