#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC

import re
import os
import sys
import glob

templ = """/*
:name: {0}
:description: Test imported from ivtest
:files: {1}
:incdirs: {4}
:tags: ivtest
{2}
{3}
{5}
*/
"""

try:
    third_party_dir = os.environ['THIRD_PARTY_DIR']
    tests_dir = os.environ['TESTS_DIR']
    conf_dir = os.environ['CONF_DIR']
except KeyError:
    print("Export the THIRD_PARTY_DIR, TESTS_DIR and CONF_DIR variables first")
    sys.exit(1)

try:
    tests_subdir = sys.argv[1]
except IndexError:
    print("Usage: ./generator <subdir>")
    sys.exit(1)

type_should_fail = ['CE', 'RE']

# FIXME: this all needs to be updated to properly load the ivtest *.list
#        files like is done with the ivtest driver along with the correct
#        override of the various tests.
ivtest_exclude = [
    'blif.list',  # Skip the BLIF test list
    'regress-ivl1.list',  # Skip the Icarus specific test list
    'regress-msys2.list',  # Skip the msys2 override test list
    'regress-v10.list',  # Skip the v10 override test list
    'regress-v11.list',  # Skip the v11 override test list
    'regress-vams.list',  # Skip the VAMS test list
    'regress-vhdl.list',  # Skip the VHDL test list
    'regress-vlog95.list',  # Skip the vlog95 override test list
    'vhdl_regress.list',  # Skip the VHDL side test list
    'vpi_regress.list'  # Skip the VPI test list
]

ivtest_blacklist = [
    'br974c',  # reg and logic is exclusive
    'br988',  # generate_item can't have begin/end
    'br_gh72b',  # should_fail test
    'ca_time',  # IV only $simtime
    'case3',  # '@ *' is invalid event_control ( '@*' or '@ (*)' is valid )
    'deposit',  # IV only $deposit
    'deposit_wire',  # IV only $deposit
    'display_bug',  # [2] is invalid range
    'elsif_test',  # ifdef must have text_macro_identifier
    'enum_ports',  # reg can't have type
    'fileio',  # IV only $fopenr and $fopenw
    'fread',  # $fread from invalid variable (per wsnyder)
    'memsynth3',  # bit is keyword
    'plus_arg_string',  # IV only $finish_and_return
    'pr478',  # `protect is not valid directive
    'pr841',  # unresolved wires
    'pr1467825',  # `suppress_faults is not valid directive
    'pr1716276',  # empty parameter is invalid
    'pr1723367',  # scalar with vectored net
    'pr1787423',  # pulldown can't have multiple terminal
    'pr1787423b',  # pulldown can't have multiple terminal
    'pr1861212a',  # reg can't have type
    'pr1877743',  # parallel_path_description can't have multiple input terminal
    'pr1978358',  # constant out of bound part select may be an error
    'pr1978358b',  # constant out of bound part select may be an error
    'pr1978358c',  # constant out of bound part select may be an error
    'pr1978358d',  # constant out of bound part select may be an error
    'pr2257003',  # generate_item can't have begin/end
    'pr2257003b',  # generate_item can't have begin/end
    'pr2790236',  # non-ANSI port can't have assignment
    'pr2834340',  # pulldown can't have multiple terminal
    'pr2834340b',  # pulldown can't have multiple terminal
    'pr3194155',  # parameter_value_assignment must have paren
    'pr3270320',  # IV only $abs
    'pr3539372',  # empty initial
    'sel_rval_bit_ob',  # constant out of bound bit select may be an error
    'sf1289',  # foreach must have statement, not statement_or_null
    'size_cast2',  # reg and logic is exclusive
    'specify_01',  # parallel_path_description can't have multiple input terminal
    'struct_packed_array',  # reg can't have type
    'sv_array_assign_pattern2',  # '{} is invalid
    'sv_casting',
    'sv_darray_args1',  # '{} is invalid
    'sv_darray_args2',  # '{} is invalid
    'sv_darray_args2b',  # '{} is invalid
    'sv_darray_args3',  # '{} is invalid
    'sv_darray_args4',  # '{} is invalid
    'sv_wildcard_import2',  # event_trigger can't have package_scope
    'sv_wildcard_import3',  # event_trigger can't have package_scope
    'undef',  # undefined macro behaviour is ambiguous
    'warn_opt_sys_tf',  # IV only $getpattern
    'wildsense',  # '@ *' is invalid event_control ( '@*' or '@ (*)' is valid )
    'z1',  # parameter_value_assignment must have paren
    'z2'  # parameter_value_assignment must have paren
]

ivtest_long = ['comp1000', 'comp1001']

ivtest_dir = os.path.abspath(os.path.join(third_party_dir, "tests", "ivtest"))
ivtest_exclude = set(
    map(lambda x: os.path.join(ivtest_dir, x), ivtest_exclude))
ivtest_lists = list(
    set(glob.glob(os.path.join(ivtest_dir, '*.list'))) - ivtest_exclude)

tests = []

skip = False

incdirs = [ivtest_dir, os.path.join(ivtest_dir, 'ivltests')]

for l in ivtest_lists:
    with open(l, 'r') as f:
        for line in f:
            if skip:
                skip = False
                continue

            # remove comments
            line = re.sub(r'#.*?\n', '', line)

            # skip multiline definitions
            if re.search(r'\\\n', line):
                skip = True
                continue

            line = line.split()

            if len(line) < 3:
                continue

            name = line[0]
            path = os.path.join(ivtest_dir, line[2], line[0] + '.v')
            should_fail_because = ''

            # sanitize name
            name = re.sub(r'\W', '', name)

            if name in ivtest_blacklist:
                continue
            if re.match("vhdl_", name):
                continue

            type_ = ''
            for t in type_should_fail:
                if re.match(t, line[1]):
                    should_fail_because = ':should_fail_because: this test was imported from ivtest and is designed to fail'
                    type_ = ':type: simulation'

            timeout = ''
            if name in ivtest_long:
                timeout = ':timeout: 30'

            tests.append(
                (
                    name + '_iv', path, should_fail_because, type_,
                    ' '.join(incdirs), timeout))

test_dir = os.path.join(tests_dir, 'generated', tests_subdir)

if not os.path.isdir(test_dir):
    os.makedirs(test_dir, exist_ok=True)

for test in tests:
    test_file = os.path.join(test_dir, test[0] + '.sv')
    with open(test_file, "w") as f:
        f.write(templ.format(*test))
