#!/usr/bin/env python3

import os
import sys

templ = """/*
:name: {0}
:description: The '{0}' keyword should be reserved
:should_fail: 1
:tags: 5.6.2
*/

module top();
    bit {0};
endmodule
"""

try:
    tests_dir = os.environ['TESTS_DIR']
    conf_dir = os.environ['CONF_DIR']
except KeyError:
    print("Export the TESTS_DIR and CONF_DIR variables first")
    sys.exit(1)

try:
    tests_subdir = sys.argv[1]
except IndexError:
    print("Usage: ./generator <subdir>")
    sys.exit(1)

conf_file = os.path.join(conf_dir, "generators", "sv-keywords.list")
with open(conf_file, "r") as f:
    for x in f:
        x = x[:-1]
        test_file = os.path.join(tests_dir,
                                 "generated",
                                 tests_subdir,
                                 "5.6.2--keyword-" + x + ".sv")
        with open(test_file, "w") as wf:
            wf.write(templ.format(x))
