#!/usr/bin/env python3

import os
import sys
import glob

templ = """/*
:name: taiga
:description: Full Taiga core test
:files: {0}
:tags: taiga
:timeout: 100
*/
"""

try:
    third_party_dir = os.environ['THIRD_PARTY_DIR']
    tests_dir = os.environ['TESTS_DIR']
    conf_dir = os.environ['CONF_DIR']
except KeyError:
    print("Export the THIRD_PARTY_DIR, TESTS_DIR and CONF_DIR variables first")
    sys.exit(1)

try:
    tests_subdir = sys.argv[1]
except IndexError:
    print("Usage: ./generator <subdir>")
    sys.exit(1)

taiga_path = os.path.abspath(os.path.join(third_party_dir, "cores", "taiga"))

dirs = [
    ['core'], ['core', 'div_algorithms'], ['l2_arbiter'], ['local_memory'],
    ['examples', 'zedboard']
]

sources = ''

for d in dirs:
    for f in glob.glob(os.path.join(taiga_path, *d, '*.sv')):
        sources += f + ' '

test_dir = os.path.join(tests_dir, 'generated', tests_subdir)

if not os.path.isdir(test_dir):
    os.makedirs(test_dir, exist_ok=True)

test_file = os.path.join(test_dir, "taiga.sv")

with open(test_file, "w") as f:
    f.write(templ.format(sources))
