#!/usr/bin/env python3

import os
import sys

templ = """/*
:name: unary_op_{1}
:description: {0} operator test
:should_fail: 0
:tags: {2}
*/
module top();

int a = 12;
int b = 5;

initial begin
    a = {0}b;
end

endmodule
"""

ops = [
    ('+', 'plus', '11.3'),
    ('-', 'minus', '11.3'),
    ('!', 'not_log', '11.3'),
    ('~', 'not_bit', '11.4.8'),
    ('&', 'and', '11.4.9'),
    ('~&', 'nand', '11.4.9'),
    ('|', 'or', '11.4.9'),
    ('~|', 'nor', '11.4.9'),
    ('^', 'xor', '11.4.9'),
    ('~^', 'xnor_1', '11.4.9'),
    ('^~', 'xnor_2', '11.4.9'),
]

try:
    tests_dir = os.environ['TESTS_DIR']
    conf_dir = os.environ['CONF_DIR']
except KeyError:
    print("Export the TESTS_DIR and CONF_DIR variables first")
    sys.exit(1)

try:
    tests_subdir = sys.argv[1]
except IndexError:
    print("Usage: ./generator <subdir>")
    sys.exit(1)

for op in ops:
    test_file = os.path.join(tests_dir,
                             "generated",
                             tests_subdir,
                             "{2}--unary_op_{1}.sv".format(*op))
    with open(test_file, "w") as wf:
        wf.write(templ.format(*op))
