#!/usr/bin/env python3

import os
import sys

templ = """/*
:name: {1}_{0}
:description: {0} statement with {1}
:should_fail: 0
:tags: 12.5.3
*/
module top();

wire [3:0] a = 3;
reg [3:0] b = 0;

initial begin
    {1} {0} (a)
        0, 1: b = 1;
        2: b = 2;
        3: b = 3;
    endcase
end

endmodule
"""

cases = ['case', 'casez', 'casex']
mods = ['unique', 'unique0', 'priority']

try:
    tests_dir = os.environ['TESTS_DIR']
    conf_dir = os.environ['CONF_DIR']
except KeyError:
    print("Export the TESTS_DIR and CONF_DIR variables first")
    sys.exit(1)

try:
    tests_subdir = sys.argv[1]
except IndexError:
    print("Usage: ./generator <subdir>")
    sys.exit(1)

for case in cases:
    for mod in mods:
        test_file = os.path.join(tests_dir,
                                 "generated",
                                 tests_subdir,
                                 "12.5.3--" + mod + '_' + case + ".sv")
        with open(test_file, "w") as wf:
            wf.write(templ.format(case, mod))
