#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2026 The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC

import sys
import os
import glob

templ = """/*
:name: {name}
:description: UVM example - {name}
:files: {0}
:incdirs: {1}
:tags: uvm-examples {uvm_tag}
:type: simulation elaboration parsing
:timeout: 900
:unsynthesizable: 1
:simvariants: {2}
:success_info: {success_info}
{extra_param}*/
"""

try:
    third_party_dir = os.environ['THIRD_PARTY_DIR']
    tests_dir = os.environ['TESTS_DIR']
except KeyError:
    print("Export the THIRD_PARTY_DIR and TESTS_DIR variables first")
    sys.exit(1)

try:
    tests_subdir = sys.argv[1]
except IndexError:
    print("Usage: ./generator <subdir>")
    sys.exit(1)

examples_path = os.path.abspath(
    os.path.join(third_party_dir, "tests", "uvm-examples"))
main_path = os.path.abspath(os.getcwd())

tests = {
    "apb_protocol_monitor": {
        "uvm_tag": "uvm",
        "files": ["protocol_monitor/apb_monitor.sv", "testbench/apb_monitor_tb.sv"],
        "incdirs": [],
        "simvariants": [],
        "success_info": "TEST PASSED"
    },
    "biquad_example": {
        "uvm_tag":
        "uvm-1.2",
        "files": [
            "rtl/biquad.sv",
            "tb/agents/signal_agent/signal_if.sv",
            "tb/agents/apb_agent/apb_if.sv",
            "tb/agents/apb_agent/apb_agent_pkg.sv",
            "tb/agents/signal_agent/signal_agent_pkg.sv",
            "tb/env/biquad_env_pkg.sv",
            "tb/registers/biquad_reg_pkg.sv",
            "tb/sequences/biquad_vseq_pkg.sv",
            "tb/test/biquad_test_pkg.sv",
            "tb/tb/biquad_tb.sv",
        ],
        "incdirs": ["tb/agents/apb_agent", "tb/agents/signal_agent", "tb/env", "tb/sequences", "tb/test"],
        "simvariants":
        ["UVM_TESTNAME=biquad_smoke_test", "UVM_TESTNAME=biquad_test"],
        "success_info": "UVM TEST PASSED"
    },
    "uart_example": {
        "uvm_tag":
        "uvm",
        "files": [
            "rtl/uart/uart_16550.sv", "rtl/uart/uart_register_file.sv",
            "rtl/uart/uart_rx_fifo.sv", "rtl/uart/uart_rx.sv",
            "rtl/uart/uart_tx_fifo.sv", "rtl/uart/uart_tx.sv",
            "agents/apb_agent/apb_if.sv", "agents/apb_agent/apb_agent_pkg.sv",
            "agents/uart_agent/serial_if.sv",
            "agents/uart_agent/uart_agent_pkg.sv",
            "agents/modem_agent/modem_if.sv",
            "agents/modem_agent/modem_agent_pkg.sv",
            "uvm_tb/register_model/uart_reg_pkg.sv",
            "uvm_tb/env/uart_env_pkg.sv",
            "uvm_tb/sequences/host_if_seq_pkg.sv",
            "uvm_tb/sequences/uart_seq_pkg.sv",
            "uvm_tb/virtual_sequences/uart_vseq_pkg.sv",
            "uvm_tb/tests/uart_test_pkg.sv", "uvm_tb/tb/interrupt_if.sv",
            "protocol_monitor/apb_monitor.sv", "uvm_tb/tb/uart_tb.sv"
        ],
        "incdirs": [
            "agents/apb_agent", "agents/uart_agent", "agents/modem_agent",
            "uvm_tb/env", "uvm_tb/sequences", "uvm_tb/sequences",
            "uvm_tb/virtual_sequences", "uvm_tb/tests"
        ],
        "simvariants": [
            "UVM_TESTNAME=uart_test", "UVM_TESTNAME=baud_rate_test",
            "UVM_TESTNAME=modem_int_test", "UVM_TESTNAME=word_format_int_test",
            "UVM_TESTNAME=modem_poll_test",
            "UVM_TESTNAME=word_format_poll_test"
        ],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_ac_config_db": {
        "uvm_tag":
        "uvm",
        "files": [
            "sfr_agent/sfr_agent_pkg.sv", "sfr_agent/sfr_master_bfm.sv",
            "sfr_agent/sfr_monitor_bfm.sv", "sfr_test_pkg/sfr_test_pkg.sv",
            "tb/hdl_top.sv", "tb/hvl_top.sv", "rtl/sfr_dut.sv"
        ],
        "incdirs": ["sfr_agent", "sfr_test_pkg"],
        "simvariants": ["UVM_TESTNAME=sfr_test"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_alu_config_analysis": {
        "uvm_tag": "uvm",
        "files": "agent/alu_agent_pkg.sv \
            agent/alu_monitor_bfm.sv \
            agent/alu_driver_bfm.sv \
            alu/alu_if.sv  alu/alu_rtl.sv\
            uvm_tb/alu_tb_pkg.sv \
            tb/hdl_top.sv  tb/hvl_top.sv",
        "incdirs": ["agent uvm_tb"],
        "simvariants": ["UVM_TESTNAME=test_all_parallel"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_c_stimulus_bl_example": {
        "uvm_tag":
        "uvm",
        "files": [
            "./c_stimulus_pkg/c_stimulus_pkg.sv",
            "./c_stimulus_pkg/isr_pkg.sv",
            "./block_level_example/rtl/spi/rtl/verilog/spi_clgen.v",
            "./block_level_example/rtl/spi/rtl/verilog/timescale.v",
            "./block_level_example/rtl/spi/rtl/verilog/spi_defines.v",
            "./block_level_example/rtl/spi/rtl/verilog/spi_shift.v",
            "./block_level_example/rtl/spi/rtl/verilog/spi_top.v",
            "./block_level_example/agents/apb_agent/apb_agent_pkg.sv",
            "./block_level_example/agents/spi_agent/spi_agent_pkg.sv",
            "./block_level_example/uvm_tb/uvm_register_model/spi_reg_pkg.sv",
            "./block_level_example/agents/apb_agent/apb_if.sv",
            "./block_level_example/agents/spi_agent/spi_if.sv",
            "./block_level_example/uvm_tb/tb/intr_if.sv",
            "./block_level_example/uvm_tb/env/spi_env_pkg.sv",
            "./block_level_example/uvm_tb/sequences/spi_bus_sequence_lib_pkg.sv",
            "./block_level_example/uvm_tb/sequences/spi_sequence_lib_pkg.sv",
            "./block_level_example/uvm_tb/sequences/spi_virtual_seq_lib_pkg.sv",
            "./block_level_example/uvm_tb/test/spi_test_lib_pkg.sv",
            "./block_level_example/uvm_tb/tb/top_tb.sv",
            "./c_stimulus_pkg/reg_api.c",
            "./block_level_example/c_code/spi_c_poll_test.c",
            "./block_level_example/c_code/spi_int_test.c",
        ],
        "incdirs": [
            "block_level_example/agents/apb_agent",
            "block_level_example/agents/spi_agent", "c_stimulus_pkg",
            "block_level_example/rtl/spi/rtl/verilog",
            "block_level_example/uvm_tb/uvm_register_model",
            "block_level_example/uvm_tb/env",
            "block_level_example/uvm_tb/sequences",
            "block_level_example/uvm_tb/test", "block_level_example/c_code"
        ],
        "simvariants":
        ["UVM_TESTNAME=spi_c_int_test", "UVM_TESTNAME=spi_c_poll_test"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_ef_vif_config_db": {
        "uvm_tag":
        "uvm",
        "files": [
            "./sfr_agent/sfr_agent_pkg.sv", "./sfr_agent/sfr_master_bfm.sv",
            "./sfr_agent/sfr_monitor_bfm.sv", "./sfr_test_pkg/sfr_test_pkg.sv",
            "./tb/hvl_top.sv", "./tb/hdl_top.sv", "./rtl/sfr_dut.sv"
        ],
        "incdirs": ["sfr_agent", "sfr_test_pkg"],
        "simvariants": ["UVM_TESTNAME=sfr_test"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_generation_seq_persistence": {
        "uvm_tag":
        "uvm",
        "files": [
            "./common/bus_if.sv", "./common/dut.sv",
            "./common/bus_agent_pkg.sv",
            "./sequence_library/bus_seq_lib_pkg.sv", "./tests/test_lib_pkg.sv",
            "./common/top_tb.sv"
        ],
        "incdirs": [],
        "simvariants": ["UVM_TESTNAME=complete_transfer_test"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_generation_seq_poly": {
        "uvm_tag":
        "uvm",
        "files": [
            "./common/bus_if.sv", "./common/dut.sv",
            "./common/bus_agent_pkg.sv",
            "./sequence_library/bus_seq_lib_pkg.sv", "./tests/test_lib_pkg.sv",
            "./common/top_tb.sv"
        ],
        "incdirs": [],
        "simvariants": ["UVM_TESTNAME=rand_transfer_test"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_generation_seq_randomization": {
        "uvm_tag":
        "uvm",
        "files": [
            "common/bus_if.sv", "common/dut.sv", "common/bus_agent_pkg.sv",
            "sequence_library/bus_seq_lib_pkg.sv", "tests/test_lib_pkg.sv",
            "common/top_tb.sv"
        ],
        "incdirs": [],
        "simvariants": ["UVM_TESTNAME=seq_rand_test"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_id_register": {
        "uvm_tag":
        "uvm",
        "files": [
            "apb_agent/apb_agent_pkg.sv",
            "apb_agent/apb_driver_bfm.sv",
            "apb_agent/apb_monitor_bfm.sv",
            "reg_dut.sv",
            "regmodel_pkg.sv",
            "uvm_tb_pkg.sv",
            "hvl_top.sv",
            "hdl_top.sv",
        ],
        "incdirs": ["apb_agent"],
        "simvariants": [],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_interrupts_parallel_processing": {
        "uvm_tag":
        "uvm",
        "files": [
            "utils/interrupt/interrupt_pkg.sv",
            "utils/interrupt/interrupt_if.sv",
            "parallel_processing/dsp_chain.sv",
            "parallel_processing/dsp_con_pkg.sv",
            "parallel_processing/dsp_con_driver_bfm.sv",
            "parallel_processing/top.sv"
        ],
        "incdirs": ["utils/interrupt", "parallel_processing"],
        "simvariants": [],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_interrupts_prioritized": {
        "uvm_tag":
        "uvm",
        "files": [
            "utils/interrupt/interrupt_pkg.sv",
            "utils/interrupt/interrupt_if.sv",
            "bidirect_bus_agent_pkg.sv",
            "prioritised/top.sv",
        ],
        "incdirs": ["utils/interrupt"],
        "simvariants": [],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_interrupts_simple": {
        "uvm_tag":
        "uvm",
        "files": [
            "utils/interrupt/interrupt_pkg.sv",
            "utils/interrupt/interrupt_if.sv",
            "bidirect_bus_agent_pkg.sv",
            "simple/top.sv",
        ],
        "incdirs": ["utils/interrupt"],
        "simvariants": [],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_many_to_one": {
        "uvm_tag":
        "uvm",
        "files": [
            "./b.sv",
            "./a.sv",
            "./c.sv",
            "./abc_layering.sv",
            "./env.sv",
            "./test.sv",
        ],
        "incdirs": ["."],
        "simvariants": ["UVM_TESTNAME=test"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_messaging_example": {
        "uvm_tag": "uvm",
        "files": ["messaging_example.sv"],
        "incdirs": [],
        "simvariants": ["UVM_TESTNAME=message_test"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_overriding": {
        "uvm_tag": "uvm",
        "files": ["a_agent_pkg.sv", "top.sv"],
        "incdirs": [],
        "simvariants": [],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_param_vif_config_db": {
        "uvm_tag":
        "uvm",
        "files": [
            "./sfr_agent/sfr_agent_pkg.sv",
            "./sfr_agent/sfr_master_bfm.sv",
            "./sfr_agent/sfr_monitor_bfm.sv",
            "./tb/tb_params_pkg.sv",
            "./sfr_test_pkg/sfr_test_pkg.sv",
            "./tb/hdl_top.sv",
            "./tb/hvl_top.sv",
            "./rtl/sfr_dut.sv",
        ],
        "incdirs": ["sfr_agent", "sfr_test_pkg"],
        "simvariants": ["UVM_TESTNAME=sfr_test"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_priority_arbitration": {
        "uvm_tag":
        "uvm",
        "files": ["top.sv"],
        "incdirs": [],
        "simvariants": [
            "ARB_TYPE=SEQ_ARB_FIFO",
            "ARB_TYPE=SEQ_ARB_WEIGHTED",
            "ARB_TYPE=SEQ_ARB_RANDOM",
            "ARB_TYPE=SEQ_ARB_STRICT_FIFO",
            "ARB_TYPE=SEQ_ARB_STRICT_RANDOM",
            "ARB_TYPE=SEQ_ARB_USER",
        ],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_priority_grab_lock": {
        "uvm_tag":
        "uvm",
        "files": ["top.sv"],
        "incdirs": [],
        "simvariants": [
            "ARB_TYPE=SEQ_ARB_FIFO",
            "ARB_TYPE=SEQ_ARB_WEIGHTED",
            "ARB_TYPE=SEQ_ARB_RANDOM",
            "ARB_TYPE=SEQ_ARB_STRICT_FIFO",
            "ARB_TYPE=SEQ_ARB_STRICT_RANDOM",
            "ARB_TYPE=SEQ_ARB_USER",
        ],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_register_mem_example": {
        "uvm_tag":
        "uvm",
        "files": [
            "./dut/timescale.v",
            "./dut/mem_ss.sv",
            "./dut/reg_defs.sv",
            "./agents/ahb_agent/ahb_agent_pkg.sv",
            "./register_model/mem_ss_reg_pkg.sv",
            "./agents/ahb_agent/ahb_monitor_bfm.sv",
            "./agents/ahb_agent/ahb_if.sv",
            "./agents/ahb_agent/ahb_driver_bfm.sv",
            "./env/mem_ss_env_pkg.sv",
            "./sequences/mem_ss_seq_lib_pkg.sv",
            "./test/mem_ss_test_lib_pkg.sv",
            "./tb/hvl_top.sv",
            "./tb/hdl_top.sv",
        ],
        "incdirs": [
            "dut",
            "agents/ahb_agent",
            "register_model",
            "env",
            "sequences",
            "test",
            "utils",
        ],
        "simvariants": ["UVM_TESTNAME=mem_ss_test"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_register_spi_bl_tb": {
        "uvm_tag":
        "uvm",
        "files": [
            "./rtl/spi/rtl/verilog/spi_clgen.v",
            "./rtl/spi/rtl/verilog/timescale.v",
            "./rtl/spi/rtl/verilog/spi_defines.v",
            "./rtl/spi/rtl/verilog/spi_shift.v",
            "./rtl/spi/rtl/verilog/spi_top.v",
            "./agents/apb_agent/apb_agent_pkg.sv",
            "./agents/spi_agent/spi_agent_pkg.sv",
            "./block_level_tbs/spi_tb/register_model/spi_reg_pkg.sv",
            "./agents/spi_agent/spi_monitor_bfm.sv",
            "./agents/spi_agent/spi_driver_bfm.sv",
            "./agents/spi_agent/spi_if.sv",
            "./agents/apb_agent/apb_driver_bfm.sv",
            "./agents/apb_agent/apb_if.sv",
            "./agents/apb_agent/apb_monitor_bfm.sv",
            "./utils/interrupt/intr_pkg.sv",
            "./utils/interrupt/intr_bfm.sv",
            "./utils/interrupt/intr_if.sv",
            "./block_level_tbs/spi_tb/env/spi_env_pkg.sv",
            "./block_level_tbs/spi_tb/sequences/spi_bus_sequence_lib_pkg.sv",
            "./block_level_tbs/spi_tb/sequences/spi_test_seq_lib_pkg.sv",
            "./block_level_tbs/spi_tb/test/spi_test_lib_pkg.sv",
            "./block_level_tbs/spi_tb/tb/hvl_top.sv",
            "./block_level_tbs/spi_tb/tb/hdl_top.sv",
        ],
        "incdirs": [
            "rtl/spi/rtl/verilog",
            "agents/apb_agent",
            "agents/spi_agent",
            "utils",
            "utils/interrupt",
            "block_level_tbs/spi_tb/env",
            "block_level_tbs/spi_tb/sequences",
            "block_level_tbs/spi_tb/test",
        ],
        "simvariants": ["UVM_TESTNAME=spi_interrupt_test"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_slave_agent": {
        "uvm_tag":
        "uvm",
        "files": [
            "agents/apb_slave_agent/apb_slave_agent_pkg.sv",
            "./agents/apb_slave_agent/apb_if.sv",
            "./agents/apb_slave_agent/apb_slave_driver_bfm.sv",
            "./agents/apb_slave_agent/apb_slave_monitor_bfm.sv",
            "./rtl/apb3_wlm_host.sv",
            "./tb/env_pkg.sv",
            "./tb/hvl_top.sv",
            "./tb/hdl_top.sv",
        ],
        "incdirs": ["agents/apb_slave_agent", "tb"],
        "simvariants": [],
        "success_info": "UVM TEST PASSED",
        "extra_param": ":runner_verilator_flags: --timescale 1ns/1ns\n"
    },
    "uvm_slave_agent_multi_seq_item": {
        "uvm_tag":
        "uvm",
        "files": [
            "./agents/apb_slave_agent/apb_if.sv",
            "./agents/apb_slave_agent/apb_slave_agent_pkg.sv",
            "./agents/apb_slave_agent/apb_slave_monitor_bfm.sv",
            "./agents/apb_slave_agent/apb_slave_driver_bfm.sv",
            "./rtl/apb3_wlm_host.sv",
            "./tb/env_pkg.sv",
            "./tb/hdl_top.sv",
            "./tb/hvl_top.sv",
        ],
        "incdirs": ["agents/apb_slave_agent", "tb"],
        "simvariants": [],
        "success_info": "UVM TEST PASSED",
        "extra_param": ":runner_verilator_flags: --timescale 1ns/1ns\n"
    },
    "uvm_tb_build_bl_tb": {
        "uvm_tag":
        "uvm",
        "files": [
            "./rtl/spi/rtl/verilog/spi_clgen.v",
            "./rtl/spi/rtl/verilog/timescale.v",
            "./rtl/spi/rtl/verilog/spi_defines.v",
            "./rtl/spi/rtl/verilog/spi_shift.v",
            "./rtl/spi/rtl/verilog/spi_top.v",
            "agents/apb_agent/apb_agent_pkg.sv",
            "agents/spi_agent/spi_agent_pkg.sv",
            "block_level_tbs/spi_tb/register_model/spi_reg_pkg.sv",
            "agents/apb_agent/apb_if.sv",
            "agents/apb_agent/apb_monitor_bfm.sv",
            "agents/apb_agent/apb_driver_bfm.sv",
            "agents/spi_agent/spi_if.sv",
            "agents/spi_agent/spi_monitor_bfm.sv",
            "agents/spi_agent/spi_driver_bfm.sv",
            "utils/interrupt/intr_pkg.sv",
            "utils/interrupt/intr_if.sv",
            "utils/interrupt/intr_bfm.sv",
            "block_level_tbs/spi_tb/env/spi_env_pkg.sv",
            "block_level_tbs/spi_tb/sequences/spi_bus_sequence_lib_pkg.sv",
            "block_level_tbs/spi_tb/sequences/spi_test_seq_lib_pkg.sv",
            "block_level_tbs/spi_tb/test/spi_test_lib_pkg.sv",
            "block_level_tbs/spi_tb/tb/hvl_top.sv",
            "block_level_tbs/spi_tb/tb/hdl_top.sv",
        ],
        "incdirs": [
            "block_level_tbs/spi_tb/env",
            "block_level_tbs/spi_tb/sequences",
            "block_level_tbs/spi_tb/register_model",
            "block_level_tbs/spi_tb/test",
            "agents/apb_agent",
            "agents/spi_agent",
            "rtl/spi/rtl/verilog",
            "utils",
            "utils/interrupt",
        ],
        "simvariants": ["UVM_TESTNAME=spi_interrupt_test"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_tb_build_ss_tb": {
        "uvm_tag":
        "uvm",
        "files": [
            "sub_system_tbs/pss_tb/tb/hdl_top.sv",
            "sub_system_tbs/pss_tb/tb/hvl_top.sv",
            "sub_system_tbs/pss_tb/tb/binder.sv",
            "sub_system_tbs/pss_tb/tb/apb_prober.sv",
            "sub_system_tbs/pss_tb/tb/intr_if.sv",
            "rtl/spi/rtl/verilog/spi_top.v",
            "rtl/spi/rtl/verilog/spi_clgen.v",
            "rtl/spi/rtl/verilog/spi_shift.v",
            "rtl/ahb2apb/rtl/ahb_apb_bridge.sv",
            "rtl/gpio/rtl/verilog/gpio_top.v",
            "rtl/icpit/rtl/icpit.v",
            "rtl/uart/rtl/uart_top.v",
            "rtl/uart/rtl/uart_apb.v",
            "rtl/uart/rtl/uart_regs.v",
            "rtl/uart/rtl/uart_transmitter.v",
            "rtl/uart/rtl/uart_receiver.v",
            "rtl/uart/rtl/uart_tfifo.v",
            "rtl/uart/rtl/uart_rfifo.v",
            "rtl/uart/rtl/raminfr.v",
            "rtl/uart/rtl/uart_sync_flops.v",
            "rtl/pss/rtl/pss.sv",
            "rtl/pss/rtl/pss_wrapper.sv",
            "agents/apb_agent/apb_agent_pkg.sv",
            "agents/spi_agent/spi_agent_pkg.sv",
            "agents/ahb_agent/ahb_agent_pkg.sv",
            "agents/gpio_agent/gpio_agent_pkg.sv",
            "agents/modem_agent/modem_agent_pkg.sv",
            "agents/uart_agent/uart_agent_pkg.sv",
            "agents/apb_agent/apb_if.sv",
            "agents/apb_agent/apb_monitor_bfm.sv",
            "agents/apb_agent/apb_driver_bfm.sv",
            "agents/spi_agent/spi_if.sv",
            "agents/spi_agent/spi_monitor_bfm.sv",
            "agents/spi_agent/spi_driver_bfm.sv",
            "agents/gpio_agent/gpio_if.sv",
            "agents/gpio_agent/gpio_monitor_bfm.sv",
            "agents/gpio_agent/gpio_driver_bfm.sv",
            "agents/ahb_agent/ahb_if.sv",
            "agents/ahb_agent/ahb_monitor_bfm.sv",
            "agents/ahb_agent/ahb_driver_bfm.sv",
            "agents/modem_agent/modem_if.sv",
            "agents/modem_agent/modem_monitor_bfm.sv",
            "agents/modem_agent/modem_driver_bfm.sv",
            "agents/uart_agent/serial_if.sv",
            "agents/uart_agent/uart_monitor_bfm.sv",
            "agents/uart_agent/uart_driver_bfm.sv",
            "utils/interrupt/intr_pkg.sv",
            "utils/interrupt/intr_bfm.sv",
            "block_level_tbs/spi_tb/register_model/spi_reg_pkg.sv",
            "block_level_tbs/gpio_tb/register_model/gpio_reg_pkg.sv",
            "sub_system_tbs/pss_tb/register_model/pss_reg_pkg.sv",
            "block_level_tbs/spi_tb/env/spi_env_pkg.sv",
            "block_level_tbs/gpio_tb/env/gpio_env_pkg.sv",
            "sub_system_tbs/pss_tb/env/pss_env_pkg.sv",
            "block_level_tbs/spi_tb/sequences/spi_bus_sequence_lib_pkg.sv",
            "block_level_tbs/spi_tb/sequences/spi_test_seq_lib_pkg.sv",
            "block_level_tbs/gpio_tb/sequences/gpio_bus_sequence_lib_pkg.sv",
            "block_level_tbs/gpio_tb/sequences/gpio_test_sequence_lib_pkg.sv",
            "sub_system_tbs/pss_tb/sequences/pss_test_seq_lib_pkg.sv",
            "sub_system_tbs/pss_tb/test/pss_test_lib_pkg.sv",
            "block_level_tbs/spi_tb/test/spi_test_lib_pkg.sv",
        ],
        "incdirs": [
            "rtl/spi/rtl/verilog",
            "block_level_tbs/spi_tb/test",
            "rtl/uart/rtl",
            "rtl/gpio/rtl/verilog",
            "agents/apb_agent",
            "agents/spi_agent",
            "agents/ahb_agent",
            "agents/gpio_agent",
            "agents/modem_agent",
            "agents/uart_agent",
            "utils",
            "utils/interrupt",
            "block_level_tbs/spi_tb/register_model",
            "block_level_tbs/gpio_tb/register_model",
            "sub_system_tbs/pss_tb/test",
            "sub_system_tbs/pss_tb/sequences",
            "block_level_tbs/gpio_tb/env",
            "block_level_tbs/gpio_tb/sequences",
            "sub_system_tbs/pss_tb/register_model",
            "block_level_tbs/spi_tb/env",
            "sub_system_tbs/pss_tb/env",
            "block_level_tbs/spi_tb/sequences",
            "block_level_tbs/gpio_tb/sequences",
        ],
        "simvariants": ["UVM_TESTNAME=pss_spi_interrupt_test"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_test_init": {
        "uvm_tag":
        "uvm",
        "files": [
            "agent_a_pkg.sv",
            "agent_b_pkg.sv",
            "agent_c_pkg.sv",
            "env_1_pkg.sv",
            "env_2_pkg.sv",
            "env_top_pkg.sv",
            "top_vseq_pkg.sv",
            "top.sv",
        ],
        "incdirs": [],
        "simvariants": ["UVM_TESTNAME=init_vseq_from_test"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_use_models_bidir_get_put": {
        "uvm_tag": "uvm",
        "files": ["top_tb.sv", "top_hdl.sv"],
        "incdirs": [],
        "simvariants": [],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_use_models_bidir_item_done": {
        "uvm_tag": "uvm",
        "files": ["top_tb.sv", "top_hdl.sv"],
        "incdirs": [],
        "simvariants": [],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_use_models_pipelined_get_put": {
        "uvm_tag":
        "uvm",
        "files": [
            "mbus_slave/mbus_types_pkg.sv",
            "pipelined_get_put/mbus_pipelined_agent/mbus_pipelined_agent_pkg.sv",
            "mbus_slave/mbus_slave.sv",
            "pipelined_get_put/mbus_pipelined_agent/mbus_pipelined_driver_bfm.sv",
            "pipelined_get_put/top_tb.sv",
            "pipelined_get_put/top_hdl.sv",
        ],
        "incdirs": ["pipelined_get_put/mbus_pipelined_agent"],
        "simvariants": [],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_use_models_pipelined_item_done": {
        "uvm_tag":
        "uvm-1.2",
        "files": [
            "./mbus_slave/mbus_slave.sv",
            "./pipelined_item_done/mbus_pipelined_agent/mbus_pipelined_agent_pkg.sv",
            "./pipelined_item_done/top.sv",
        ],
        "incdirs": ["pipelined_item_done/mbus_pipelined_agent"],
        "simvariants": [],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_use_models_unidirectional": {
        "uvm_tag": "uvm",
        "files": ["top_tb.sv", "top_hdl.sv"],
        "incdirs": [],
        "simvariants": [],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_vif_config_db": {
        "uvm_tag":
        "uvm",
        "files": [
            "sfr_agent/sfr_agent_pkg.sv",
            "sfr_agent/sfr_if.sv",
            "sfr_test_pkg/sfr_test_pkg.sv",
            "tb/hdl_top.sv",
            "tb/hvl_top.sv",
            "rtl/sfr_dut.sv",
        ],
        "incdirs": ["sfr_agent", "sfr_test_pkg"],
        "simvariants": ["UVM_TESTNAME=sfr_test"],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_virt_seq_find_all": {
        "uvm_tag": "uvm-1.2",
        "files": ["simple_ovc/simple_pkg.sv", "top.sv"],
        "incdirs": ["simple_ovc"],
        "simvariants": [],
        "success_info": "UVM TEST PASSED"
    },
    "uvm_wait_for_signal": {
        "uvm_tag":
        "uvm",
        "files": [
            "bus_if.sv",
            "bidirect_bus_pkg.sv",
            "bidirect_bus_driver_bfm.sv",
            "top.sv",
        ],
        "incdirs": [],
        "simvariants": [],
        "success_info": "UVM TEST PASSED"
    },
}

for dir in os.scandir(examples_path):
    if dir.name == ".git" or dir.name == "LICENSE":
        continue
    test_name = dir.name
    test = tests[test_name]
    test_dir = os.path.join(tests_dir, 'generated', tests_subdir)
    if not os.path.isdir(test_dir):
        os.makedirs(test_dir, exist_ok=True)
    test_file = os.path.join(test_dir, dir.name + ".sv")
    files = [
        os.path.join(examples_path, test_name, name) for name in test["files"]
    ]
    incdirs = [
        os.path.join(examples_path, test_name, name)
        for name in test["incdirs"]
    ]
    if "extra_param" in test:
        extra_param = test["extra_param"]
    else:
        extra_param = ""
    with open(test_file, "w") as f:
        f.write(
            templ.format(
                " ".join(files),
                " ".join(incdirs),
                " ".join(test["simvariants"]),
                name=dir.name,
                uvm_tag=test["uvm_tag"],
                success_info=test["success_info"],
                extra_param=extra_param
            ))
