#!/usr/bin/env python3

# Copyright (C) 2020 The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC

import os
import sys
import argparse
import logging

from importlib import import_module

parser = argparse.ArgumentParser()

parser.add_argument("runners", metavar='runner', type=str, nargs='+')

args = parser.parse_args()
logger = logging.getLogger()

runner_obj = None

runners_ok = []

if 'RUNNERS_DIR' in os.environ:
    sys.path.insert(1, os.path.abspath(os.environ['RUNNERS_DIR']))

for runner in args.runners:
    try:
        module = import_module(runner)
        runner_cls = getattr(module, runner)
        runner_obj = runner_cls()
    except Exception:
        continue

    new_path = [
        os.path.abspath(os.environ['OUT_DIR'] + "/runners/bin/"),
        os.environ['PATH']
    ]

    os.environ['PATH'] = ":".join(new_path)

    if runner_obj.can_run():
        print(runner)
    else:
        logger.debug('Runner {} not found'.format(runner))
