#!/usr/bin/env python3

import os
import argparse
from pygments import lexers, highlight
from pygments.formatters import HtmlFormatter

parser = argparse.ArgumentParser()

parser.add_argument("outdir")

parser.add_argument("files", metavar='file',
                    type=str, nargs='+')

args = parser.parse_args()

lex = lexers.get_lexer_by_name("systemverilog")
formatter = HtmlFormatter(full=True, linenos=True)

for fname in args.files:
    with open(fname, 'rb') as f:
        code = f.read()
        path = os.path.join(args.outdir, fname + '.html')
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w') as out:
            highlight(code, lex, formatter, outfile=out)
