#!/usr/bin/env python3

import os
import re
import sys
import shutil
import logging
import argparse
import tempfile
from importlib import import_module
from logparser import parseLog

parser = argparse.ArgumentParser()

parser.add_argument("-r", "--runner", required=True)

action = parser.add_mutually_exclusive_group(required=True)
action.add_argument("-t", "--test")
action.add_argument("-v", "--version", action="store_true")

parser.add_argument("-o", "--out", required=True)

parser.add_argument(
    "-q",
    "--quiet",
    dest='verbosity',
    action='store_const',
    const=logging.ERROR,
    default=logging.DEBUG)

args = parser.parse_args()

# setup logger
logger = logging.getLogger()
logger.setLevel(args.verbosity)

ch = logging.StreamHandler()
ch.setFormatter(logging.Formatter('%(levelname)-8s| %(message)s'))
logger.addHandler(ch)

runner_obj = None

try:
    module = import_module('runners.' + args.runner)
    runner_cls = getattr(module, args.runner)
    runner_obj = runner_cls()
except Exception as e:
    logger.error("Unable to load runner module: {}".format(str(e)))
    sys.exit(1)

dirs = {}

try:
    dirs['out'] = os.environ['OUT_DIR']
    dirs['tests'] = os.environ['TESTS_DIR']
    dirs['runners'] = os.environ['RUNNERS_DIR']
except KeyError as e:
    logger.error("Required environment variables missing: {}".format(str(e)))
    sys.exit(1)

new_path = [os.path.abspath(dirs['out'] + "/runners/bin/"), os.environ['PATH']]

os.environ['PATH'] = ":".join(new_path)

runner = os.path.abspath(os.path.join(dirs['runners'], args.runner))
out = os.path.abspath(args.out)

os.makedirs(os.path.dirname(out), exist_ok=True)

if args.version:
    version = runner_obj.get_version()
    with open(out, "w") as f:
        f.write(version)

    sys.exit(0)

test = os.path.abspath(os.path.join(dirs['tests'], args.test))

req_test_params = [
    "name", "tags", "description", "should_fail", "files", "incdirs",
    "top_module", "timeout", "type"
]

test_params = {}

# look for all required params
try:
    with open(test) as f:
        for l in f:
            param = re.search(r"^:([a-zA-Z_-]+):\s*(.+)", l)

            if param is None:
                continue

            param_name = param.group(1).lower()
            param_value = param.group(2)

            if param_name not in req_test_params:
                logger.warning(
                    "Unsupported test param found: {} - ignoring".format(
                        param_name))
                continue

            test_params[param_name] = param_value

            if len(set(req_test_params) - set(test_params.keys())) == 0:
                # all parameters found
                break

        else:
            # set default values for optional metadata entries
            test_params.setdefault('files', test)
            test_params.setdefault('incdirs', os.path.dirname(test))
            test_params.setdefault('top_module', '')
            test_params.setdefault('timeout', "10")
            test_params.setdefault('type', 'parsing')

            if len(set(req_test_params) - set(test_params.keys())) != 0:
                missing = list(set(req_test_params) - set(test_params.keys()))
                logger.error(
                    "Required parameters missing ({}) in {}".format(
                        ", ".join(missing), args.test))
                sys.exit(1)
except Exception as e:
    logger.error("Unable to parse test file: {}".format(str(e)))
    sys.exit(1)

test_params['files'] = test_params['files'].split()
test_params['incdirs'] = list(
    map(
        lambda x: os.path.abspath(os.path.join(dirs['tests'], x)),
        test_params['incdirs'].split()))

test_params['mode'] = runner_obj.get_mode(test_params['type'].split())

if test_params['mode'] is None:
    logger.info("Skipping {}/{}".format(args.runner, args.test))
    with open(out, "w") as f:
      f.write("")  # runner does not support mode; just mark file as handled.

    sys.exit(0)

try:
    tmp_dir = tempfile.mkdtemp()
except (PermissionError, FileExistsError) as e:
    logger.error(
        "Unable to create a temporary directory for test: {}".format(str(e)))
    sys.exit(1)

try:
    logger.info("Running {}/{}".format(args.runner, args.test))

    output, rc, user_time, system_time, ram_usage = runner_obj.run(
        tmp_dir, test_params)

    test_params['rc'] = rc
    test_params['runner'] = runner_obj.name
    test_params['runner_url'] = runner_obj.url
    test_params['time_elapsed'] = str(user_time + system_time)
    test_params['user_time'] = user_time
    test_params['system_time'] = system_time
    test_params['ram_usage'] = ram_usage

    tool_should_fail = test_params["should_fail"] == "1"
    tool_failed = test_params["rc"] != 0

    test_passed = rc < 126 and tool_should_fail == tool_failed

    if test_passed and test_params['mode'] == 'simulation':
        test_passed = parseLog(output)

    if test_passed:
        logger.info("PASS: {}/{}".format(args.runner, args.test))
    else:
        logger.warning("FAIL: {}/{}".format(args.runner, args.test))

    os.makedirs(os.path.dirname(out), exist_ok=True)

    test_params['files'] = ' '.join(test_params['files'])
    test_params['incdirs'] = ' '.join(test_params['incdirs'])

    with open(out, "w") as log:
        # start by writing params
        for p in test_params:
            log.write("{}: {}\n".format(p, test_params[p]))
        log.write("\n")
        log.write(output)
except Exception as e:
    logger.error(
        "Unable to test {} using {}: {}".format(
            args.runner, args.test, str(e)))
    sys.exit(1)
finally:
    shutil.rmtree(tmp_dir)
