#!/usr/bin/env python3

from pygments.formatters import HtmlFormatter
from pygments import lexers, highlight
from glob import glob
import argparse
import logging
import jinja2
import csv
import sys
import os
import re

parser = argparse.ArgumentParser()

logger_args = parser.add_mutually_exclusive_group()

logger_args.add_argument("-q", "--quiet",
                         action="store_true",
                         help="Disable all logs")

logger_args.add_argument("-v", "--verbose",
                         action="store_true",
                         help="Verbose logging")

parser.add_argument("-i", "--input",
                    help="Input database/LRM",
                    default="conf/lrm.conf")

parser.add_argument("-l", "--logs",
                    help="Directory with all the individual test results",
                    default="out/logs")

parser.add_argument("--template",
                    help="Path to the html report template",
                    default="conf/report/report-template.html")

parser.add_argument("--code-template",
                    help="Path to the html code preview template",
                    default="conf/report/code-template.html")

parser.add_argument("--log-template",
                    help="Path to the html log template",
                    default="conf/report/log-template.html")

parser.add_argument("-o", "--out",
                    help="Path to the html file with the report",
                    default="out/deploy/index.html")

parser.add_argument("-c", "--csv",
                    help="Path to the csv file with the report",
                    default="out/deploy/report.csv")

parser.add_argument("-r", "--revision",
                    help="Report revision",
                    default="unknown")

# parse args
args = parser.parse_args()

# setup logger
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)

ch = logging.StreamHandler()
ch.setFormatter(logging.Formatter('%(levelname)-8s| %(message)s'))
logger.addHandler(ch)

if args.quiet:
    logger.setLevel(logging.ERROR)
elif args.verbose:
    logger.setLevel(logging.DEBUG)
else:
    logger.setLevel(logging.INFO)

tag_usage = {}

lex = lexers.get_lexer_by_name("systemverilog")


def exists_and_is_newer_than(b, a):
    return os.path.exists(b) and os.path.getctime(b) > os.path.getctime(a)


def formatSrc(ifile, ofile):
    if exists_and_is_newer_than(ofile, ifile):
        return

    formatter = HtmlFormatter(full=False, linenos=True,
                              anchorlinenos=True, lineanchors='l')
    with open(ifile, 'rb') as f:
        raw_code = f.read()
        os.makedirs(os.path.dirname(ofile), exist_ok=True)

        with open(args.code_template, "r") as tl:
            template = jinja2.Template(tl.read(),
                                       trim_blocks=True,
                                       lstrip_blocks=True)

        code = highlight(raw_code, lex, formatter)

        with open(ofile, 'w') as out:
            filename = os.path.relpath(ifile)
            src_rel = "../" * filename.count('/')
            csspath = os.path.join(src_rel, "code.css")

            out.write(template.render(csspath=csspath,
                                      filename=filename,
                                      code=code))


def logToHTML(path_in, path_out, tags):
    depth = path_in.count('/') - 1
    src_relative = '../' * depth
    files = tags['files'].split()
    log = tags['log']
    html_pat_ln = r'{}:(\d+)'
    html_sub_ln = r'<a href="{0}{1}.html#l-\1" target="file-frame">{1}:\1</a>'

    tags['tool'] = "toolname"
    tags['tool_url'] = "toolname.pl"

    tags['file_urls'] = []

    for f in files:
        f_rel = os.path.relpath(f)
        f_html = ('<a href="{0}{1}.html" target="file-frame">{1}</a>'
                  .format(src_relative, f_rel))
        log = re.sub(html_pat_ln.format(f),
                     html_sub_ln.format(src_relative, f_rel), log)
        log = re.sub(f, f_html, log)
        formatSrc(f, os.path.join(os.path.dirname(args.out),
                  f_rel + '.html'))

        tags['file_urls'].append(f_html)

    tags['file_urls'] = " ".join(tags['file_urls'])
    tags['log_urls'] = log

    with open(args.log_template, "r") as templ:
        logf = jinja2.Template(templ.read(),
                               trim_blocks=True,
                               lstrip_blocks=True)

    with open(path_out + ".html", 'w') as html:
        html.write(logf.render(**tags))

    return os.path.relpath(files[0]) + '.html'


def getRelativePaths(paths):
    paths = paths.split(' ')
    paths = list(map(lambda x: os.path.realpath(x), paths))

    return ' '.join(paths)


# generate input database first
database = {}
try:
    with open(args.input) as f:
        for l in f:
            ls = l.strip()
            # skip lines with comments
            if re.search(r"^\s*#.*", ls) is not None:
                continue

            entry = ls.split("\t")

            if len(entry) < 2:
                raise KeyError("Invalid entry: " + ls)

            database[entry[0]] = "\t".join(entry[1:])
except KeyError as e:
    # TODO: exit on error/critical handler
    logger.critical("Unable to parse the database - " + str(e))
    sys.exit(1)

logger.info("Generating {} from log files in '{}'".format(args.out, args.logs))

for tag in database:
    tag_usage[tag] = 0

data = {}

for r in [os.path.dirname(r) for r in glob(args.logs + "/*/")]:
    r_name = os.path.basename(r)
    logger.debug("Found Runner: " + r_name)
    data[r_name] = {}

    # all tests info
    data[r_name]["tests"] = {}
    tests = data[r_name]["tests"]

    for t in glob(os.path.join(args.logs, r_name, "**/*.log"), recursive=True):
        t_id = t[len(args.logs) + 1:]
        logger.debug("Found log: " + t_id)

        tests[t_id] = {}

        test_tags = ["name", "tags", "should_fail", "rc",
                     "description", "files", "incdirs",
                     "top_module", "runner", "runner_url"]
        with open(t, "r") as f:
            try:
                for l in f:
                    tag = re.search(r"^([a-zA-Z_-]+):(.+)", l)

                    if tag is None:
                        raise KeyError("Could not find tags: {}"
                                       .format(", ".join(test_tags)))

                    param = tag.group(1).lower()
                    value = tag.group(2).strip()

                    if param in test_tags:
                        test_tags.remove(param)
                        tests[t_id][param] = value

                        if len(test_tags) == 0:
                            # found all tags
                            break
                    else:
                        logger.warning(
                                "Skipping unknown parameter: {} in {}"
                                .format(param, t))

            except Exception as e:
                logger.warning("Skipping {} on {}: {}"
                               .format(t, r_name, str(e)))
                del tests[t_id]
                continue

            tests[t_id]["log"] = f.read()
            tests[t_id]["fname"] = os.path.join('logs', t_id + '.html')

            t_html = t.replace(args.logs,
                               os.path.join(os.path.dirname(args.out), "logs"))
            os.makedirs(os.path.dirname(t_html), exist_ok=True)

            tests[t_id]["first_file"] = logToHTML(t, t_html, tests[t_id])

        # check if test was skipped
        if t_id not in tests:
            continue

        # Initialize the tag-based side of the result dict
        data[r_name]["tags"] = {}
        tags = data[r_name]["tags"]

        for tag in database:
            tags[tag] = {}
            tags[tag]["status"] = []

        # generate tags summary
        for _, test in tests.items():
            # check if test has passed
            passed = True

            tool_should_fail = test["should_fail"] == "1"
            tool_failed = test["rc"] != "0"

            if int(test["rc"]) >= 126 or tool_should_fail != tool_failed:
                passed = False

            status = "test-" + ("passed" if passed else "failed")
            test["status"] = status

            if passed:
                logger.debug("{} passed {} in {}"
                             .format(r_name, test["tags"], test["name"]))
            else:
                logger.debug("{} failed {} in {}"
                             .format(r_name, test["tags"], test["name"]))

            for tag in test["tags"].split(" "):
                try:
                    tag_usage[tag] += 1
                    tags[tag]["status"].append(status)
                except KeyError:
                    logger.warning("Tag not present in the database: " + tag)
                    database[tag] = ''
                    tag_usage[tag] = 1
                    tags[tag] = {}
                    tags[tag]["status"] = [status]
                    continue

        for tag in tags:
            tags[tag]["passed-num"] = tags[tag]["status"].count("test-passed")

            if len(tags[tag]["status"]) == 0:
                tags[tag]["status"] = "test-na"
            elif all(tags[tag]["status"][0] == x for x in tags[tag]["status"]):
                tags[tag]["status"] = tags[tag]["status"][0]
            else:
                tags[tag]["status"] = "test-varied"

for tag in tag_usage:
    if tag_usage[tag] == 0:
        del database[tag]

csv_header = ['name', 'files', 'tags']
csv_output = {}
duplicates = []

for r in data:
    csv_header.append(r)
    for test in data[r]["tests"]:
        test_handle = data[r]["tests"][test]
        name = test_handle["name"]
        files = getRelativePaths(test_handle["files"])

        try:
            if csv_output[name]["files"] != files:
                logger.error("Duplicate test: {}, first use: {}, second: {}"
                             .format(name, csv_output[name]["files"],
                                     files))
                if name not in duplicates:
                    duplicates.append(name)
            else:
                csv_output[name][r] = test_handle["status"] == "test-passed"
        except KeyError:
            csv_output[name] = {}
            csv_output[name]["name"] = test_handle["name"]
            csv_output[name]["files"] = files
            csv_output[name]["tags"] = test_handle["tags"]
            csv_output[name][r] = test_handle["status"] == "test-passed"

if len(duplicates) > 0:
    logger.critical("Unable to generate report, duplicate test names")
    sys.exit(1)

try:
    for r in data:
        for tag in data[r]["tags"]:
            tag_handle = data[r]["tags"][tag]

            tag_handle["logs"] = {}

            for test in data[r]["tests"]:
                test_handle = data[r]["tests"][test]
                if tag in test_handle["tags"].split():
                    tag_handle["logs"][test] = {}
                    inner = tag_handle["logs"][test]
                    inner["log"] = test_handle["log"].replace("\n", "</br>")
                    inner["status"] = test_handle["status"]
                    inner["name"] = test_handle["name"]
                    inner["fname"] = test_handle["fname"]
                    inner["first_file"] = test_handle["first_file"]
        data[r]["total"] = {}

        # find the number of tests that passed
        rts = data[r]["tests"]
        data[r]["total"]["tests"] = sum(
                1 for t in rts if rts[t]["status"] in "test-passed")

        # find the number of tags for which all the tests passed
        rtt = data[r]["tags"]
        data[r]["total"]["tags"] = sum(
                1 for t in rtt if rtt[t]["status"] in "test-passed")

    with open(args.template, "r") as f:
        report = jinja2.Template(f.read(),
                                 trim_blocks=True,
                                 lstrip_blocks=True)

    with open(args.out, 'w') as f:
        f.write(report.render(report=data,
                              database=database,
                              revision=args.revision))

    with open(args.csv, 'w', newline='') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=csv_header)
        writer.writeheader()
        for test in csv_output:
            writer.writerow(csv_output[test])
except KeyError:
    logger.critical("Unable to generate report, not enough logs")
except Exception as e:
    logger.critical("Unable to generate report: " + str(e))
