#!/bin/bash

echo "I AM A FAKE RUNNER!"
echo "MY INVOKATION ARGS: $@"
>&2 echo "stderr test"

# return the expected result
SHOULD_FAIL=$(grep -m 1 :should_fail: $1 | cut -d' ' -f2-)

if [[ $SHOULD_FAIL -eq "1" ]]; then
  exit 1
else
  exit 0
fi
